#!/bin/bash

set -eo pipefail

SOURCE_DIR="/home/tomboyo"
RSYNC_DIR="/home/tomboyo.rsync"

case $1 in
  add)
    SOURCE=$(realpath "${2:?usage: backups add <file>}")
    
    BASE="$SOURCE_DIR/"
    if [[ $SOURCE != $BASE* ]] ; then
      echo "Cannot backup $SOURCE because it is not in $BASE."
      exit 1
    fi
    
    DEST="$RSYNC_DIR/${SOURCE#$BASE}"
    mkdir -p $(dirname $DEST)
    mv $SOURCE $DEST
    ln -s $DEST $SOURCE
    ;;
  synch)
    FROM=$RSYNC_DIR
    TO="/run/media/tomboyo/Bones/backups/rsync"
    echo "WARNING"
    echo "Synchronization will delete files from the backup if they were "
    echo "removed since the last synchronization. If you incompletely"
    echo "recover your drive and then run synch, files may be peremenantly"
    echo "lost."
    echo
    read -p "Synchronizing $FROM with $TO. Do you wish to proceed? [y/N]" -n 1 -r
    echo

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
      rsync --archive --delete $FROM $TO
    fi
    ;;
  *)
    echo "Unknown command $1"
    exit 1
    ;;
esac
